SELECT * FROM EMP;
SELECT * FROM DEPT;

-- EMP 와 DEPT 를 조인해서, 사원명, 부서번호, 부서명 조회
SELECT E.ENAME, E.DEPTNO, D.DNAME
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

-- EMP 의 COMM이 NULL이 아닌 사원의 ENAME, SAL, COMM, DEPT의 LOC를 조회
SELECT E.ENAME, E.SAL, E.COMM, D.LOC
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.COMM IS NOT NULL;

-- LOC가 'NEW YORK'이거나 'DALLAS'인 부서에 근무하는 사원들의 부서별 급여 합계와 부서명 조회
SELECT SUM(E.SAL), D.LOC, D.DNAME
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO
HAVING D.LOC='NEW YORK' or D.LOC='DALLAS';
-- 강사님 방법
SELECT D.DNAME, SUM(E.SAL)
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC IN ('NEW YORK', 'DALLAS')
GROUP BY E.DEPTNO;



