SELECT * FROM BOARD;
SELECT * FROM BOARD_FILE;
SELECT * FROM BOARD_CODE;

-- BOARD와 BOARD_CODE 테이블 CODE 기준으로 조인
SELECT * 
FROM BOARD B 
JOIN BOARD_CODE C ON B.CODE = C.CODE;
-- BOARD와 BOARD_CODE 테이블을 CODE 기준으로 조인하고 CODE가 Q인 레코드 제외
SELECT * 
FROM BOARD B 
JOIN BOARD_CODE C ON B.CODE = C.CODE
WHERE B.CODE != 'Q';
-- BOARD와 BOARD_CODE 테이블 CODE 기준으로 조인하고 USE_YN이 'Y'인 레코드만 조회
SELECT * 
FROM BOARD B 
JOIN BOARD_CODE C ON B.CODE = C.CODE
WHERE C.USE_YN = 'Y';

-- BOARD 의 SEQ_NO 와 BOARD_FILE의 BOARD_SEQ_NO을 BOARD를 기준으로 조인
SELECT  B.SEQ_NO, B.TITLE, B.CONTENT, F.BOARD_SEQ_NO, F.FILE_NAME, F.FILE_SIZE
FROM BOARD B
LEFT JOIN BOARD_FILE F ON B.SEQ_NO = F.BOARD_SEQ_NO;

-- BOARD의 SEQ_NO 와 BOARD_FILE의 BOARD_SEQ_NO을 BOARD를 기준으로 조인하고 BOARD의 CODE와 BOARD_CODE의 CODE를 조인하시오.
SELECT  B.SEQ_NO, B.TITLE, B.CONTENT, F.BOARD_SEQ_NO, F.FILE_NAME, F.FILE_SIZE, C.CODE, C.USE_YN
FROM BOARD B
LEFT JOIN BOARD_FILE F ON B.SEQ_NO = F.BOARD_SEQ_NO
JOIN BOARD_CODE C ON B.CODE = C.CODE;





