CREATE TABLE SCHOOL (
NUM INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
AREA VARCHAR(50),
COURSE_CNT INT,
C_DATE DATETIME
);

CREATE TABLE COURSE01 (
NUM INT PRIMARY KEY AUTO_INCREMENT,
SCHOOL_NUM INT,
NAME VARCHAR(50),
STUDENT_CNT INT,
C_DATE DATETIME,
FOREIGN KEY (SCHOOL_NUM) REFERENCES SCHOOL(NUM));

INSERT INTO SCHOOL VALUES (NULL, '서울대학교', '서울', 35, '80/07/01');
INSERT INTO SCHOOL VALUES (NULL, '중앙대학교', '서울', 27, '81/08/01');
INSERT INTO SCHOOL VALUES (NULL, '동아대학교', '부산', 32, '82/09/01');
INSERT INTO SCHOOL VALUES (NULL, '부산대학교', '부산', 21, '83/10/01');

INSERT INTO COURSE01 VALUES (NULL, 4, 'IT', 50, '00/07/09');
INSERT INTO COURSE01 VALUES (NULL, 3, '경영', 60, '10/01/01');
INSERT INTO COURSE01 VALUES (NULL, 2, '식품영양', 70, '09/03/01');
INSERT INTO COURSE01 VALUES (NULL, 1, '화학', 80, '08/05/01');

SELECT * FROM SCHOOL WHERE AREA = '부산';
SELECT * FROM SCHOOL WHERE COURSE_CNT BETWEEN 26 AND 30;
SELECT * FROM SCHOOL WHERE AREA LIKE '%서울%' OR NAME LIKE '%서울%';
SELECT * FROM SCHOOL WHERE C_DATE LIKE '____-08-%';
SELECT * FROM SCHOOL WHERE MONTH(C_DATE) = 8;

SELECT * FROM COURSE01 WHERE STUDENT_CNT >= 60;
SELECT * FROM COURSE01 WHERE C_DATE < '2002-04-01';
SELECT * FROM COURSE01 WHERE NAME LIKE '%영%';
SELECT NAME, DATE_FORMAT(C_DATE, '%Y-%m-%d') DATE_FORMAT FROM COURSE01;


